In [38]:
import numpy as np
from plyfile import PlyData

# Define SH constants
SH_C0 = 0.28209479177387814
SH_C1 = 0.4886025119029199
SH_C2 = np.array([
    1.0925484305920792,
    -1.0925484305920792,
    0.31539156525252005,
    -1.0925484305920792,
    0.5462742152960396
])
SH_C3 = np.array([
    -0.5900435899266435,
    2.890611442640554,
    -0.4570457994644658,
    0.3731763325901154,
    -0.4570457994644658,
    1.445305721320277,
    -0.5900435899266435
])

def get_sh_vec3(sh_coeffs, gaussianIndex, coeffIndex):
    # Assuming 16 coefficients per gaussian
    return sh_coeffs[gaussianIndex, coeffIndex, :]

def compute_sh(sh_coeffs, pos, gaussianIndex, camPos):
    # pos and camPos are numpy arrays of shape (3,)
    ray_direction = pos - camPos
    norm = np.linalg.norm(ray_direction)
    if norm == 0:
        return np.zeros(3)
    ray_direction /= norm
    x, y, z = ray_direction

    c = SH_C0 * get_sh_vec3(sh_coeffs, gaussianIndex, 0)

    c -= SH_C1 * get_sh_vec3(sh_coeffs, gaussianIndex, 1) * y
    c += SH_C1 * get_sh_vec3(sh_coeffs, gaussianIndex, 2) * z
    c -= SH_C1 * get_sh_vec3(sh_coeffs, gaussianIndex, 3) * x

    c += SH_C2[0] * get_sh_vec3(sh_coeffs, gaussianIndex, 4) * x * y
    c += SH_C2[1] * get_sh_vec3(sh_coeffs, gaussianIndex, 5) * y * z
    c += SH_C2[2] * get_sh_vec3(sh_coeffs, gaussianIndex, 6) * (2.0 * z * z - x * x - y * y)
    c += SH_C2[3] * get_sh_vec3(sh_coeffs, gaussianIndex, 7) * z * x
    c += SH_C2[4] * get_sh_vec3(sh_coeffs, gaussianIndex, 8) * (x * x - y * y)

    c += SH_C3[0] * get_sh_vec3(sh_coeffs, gaussianIndex, 9) * (3.0 * x * x - y * y) * y
    c += SH_C3[1] * get_sh_vec3(sh_coeffs, gaussianIndex, 10) * x * y * z
    c += SH_C3[2] * get_sh_vec3(sh_coeffs, gaussianIndex, 11) * (4.0 * z * z - x * x - y * y) * y
    c += SH_C3[3] * get_sh_vec3(sh_coeffs, gaussianIndex, 12) * z * (2.0 * z * z - 3.0 * x * x - 3.0 * y * y)
    c += SH_C3[4] * get_sh_vec3(sh_coeffs, gaussianIndex, 13) * x * (4.0 * z * z - x * x - y * y)
    c += SH_C3[5] * get_sh_vec3(sh_coeffs, gaussianIndex, 14) * (x * x - y * y) * z
    c += SH_C3[6] * get_sh_vec3(sh_coeffs, gaussianIndex, 15) * x * (x * x - 3.0 * y * y)

    c += 0.5

    # Clamp negative values to 0
    c = np.maximum(c, 0.0)
    return c

def compute_sh_for_vertex(input_ply_path, i, camPos):
    # Read the PLY file
    ply_data = PlyData.read(input_ply_path)
    vertex_data = ply_data['vertex'].data

    num_vertices = len(vertex_data)
    if i < 0 or i >= num_vertices:
        raise ValueError(f"Index i={i} is out of valid range. Total vertices: {num_vertices}")

    print("Total number of vertices:", num_vertices)

    # Extract the position of the i-th vertex
    pos_i = np.array([vertex_data['x'][i], vertex_data['y'][i], vertex_data['z'][i]])
    print(f"Position of vertex {i}:", pos_i)

    # Extract SH coefficients for the i-th vertex
    coeffs_i = np.zeros((16, 3), dtype=np.float32)

    # First coefficient: f_dc_0, f_dc_1, f_dc_2
    coeffs_i[0, :] = [vertex_data['f_dc_0'][i], vertex_data['f_dc_1'][i], vertex_data['f_dc_2'][i]]

    # Next 15 coefficients: f_rest_0 ~ f_rest_44 (15*3 = 45 values)
    for k in range(1, 16):
        start = (k - 1) * 3
        coeffs_i[k, 0] = vertex_data[f'f_rest_{start}'][i]
        coeffs_i[k, 1] = vertex_data[f'f_rest_{start+1}'][i]
        coeffs_i[k, 2] = vertex_data[f'f_rest_{start+2}'][i]
    print(f"SH coefficients for vertex {i} (coeffs_i):\n", coeffs_i)

    # Create SH coefficients array for a single vertex
    sh_coeffs = np.zeros((1, 16, 3), dtype=np.float32)
    sh_coeffs[0, :, :] = coeffs_i

    # Compute SH color for the vertex
    color_i = compute_sh(sh_coeffs, pos_i, 0, camPos)
    print(f"SH color for gaussian {i}:", color_i)

input_ply_path = './ply_files/point_cloud.ply'
camPos = np.array([0.0, 0.0, 10.0])
compute_sh_for_vertex(input_ply_path, 16, camPos)


Total number of vertices: 998988
Position of vertex 16: [-0.23435153  1.1573098   2.2420747 ]
SH coefficients for vertex 16 (coeffs_i):
 [[ 1.376591    1.1266575   0.6368504 ]
 [-0.06764841  0.00869221 -0.08233414]
 [ 0.00609322 -0.0372749  -0.00419052]
 [-0.06378158  0.08364501 -0.0531214 ]
 [-0.0176786  -0.00446419  0.0038806 ]
 [ 0.01363377  0.05966755 -0.02431767]
 [-0.07421682 -0.00590224 -0.06767955]
 [ 0.02044293 -0.04449234 -0.00907633]
 [-0.04831173  0.06631435 -0.07871164]
 [-0.00980973 -0.00182487  0.00495447]
 [ 0.01500243  0.05236946 -0.01401237]
 [-0.06940999 -0.02207497 -0.04368429]
 [ 0.02515462 -0.03537852 -0.0140808 ]
 [-0.02785979  0.06424847 -0.08181114]
 [-0.00266815  0.00937918 -0.00328765]
 [ 0.01790021  0.05380499 -0.02710784]]
SH color for gaussian 16: [0.8455225  0.87772584 0.65956086]
